/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pikachu;

import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.border.LineBorder;

/**
 *
 * @author Thang
 */
public class avatar extends javax.swing.JFrame {
private String link;
    /**
     * Creates new form avatar
     */
    public avatar() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        setTitle("Pick Your Avatar");
        avatar.setBorder(new LineBorder(Color.yellow, 2));
        anh1.setBorder(new LineBorder(Color.yellow, 2));
        anh2.setBorder(new LineBorder(Color.blue, 2));
        anh3.setBorder(new LineBorder(Color.red, 2));
        anh4.setBorder(new LineBorder(Color.GREEN, 2));
        setdata();
    }

    public void setdata() {
        anh1.setIcon(new ImageIcon(new ImageIcon(getClass().getResource(StaticFinalvariable.image[0])).getImage().getScaledInstance(60, 60, Image.SCALE_DEFAULT)));
        anh2.setIcon(new ImageIcon(new ImageIcon(getClass().getResource(StaticFinalvariable.image[1])).getImage().getScaledInstance(60, 60, Image.SCALE_DEFAULT)));
        anh3.setIcon(new ImageIcon(new ImageIcon(getClass().getResource(StaticFinalvariable.image[2])).getImage().getScaledInstance(60, 60, Image.SCALE_DEFAULT)));
        anh4.setIcon(new ImageIcon(new ImageIcon(getClass().getResource(StaticFinalvariable.image[3])).getImage().getScaledInstance(60, 60, Image.SCALE_DEFAULT)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        avatar = new javax.swing.JLabel();
        save = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        anh1 = new javax.swing.JButton();
        anh2 = new javax.swing.JButton();
        anh3 = new javax.swing.JButton();
        anh4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        save.setText("save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        cancel.setText("cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        anh1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anh1ActionPerformed(evt);
            }
        });

        anh2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anh2ActionPerformed(evt);
            }
        });

        anh3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anh3ActionPerformed(evt);
            }
        });

        anh4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anh4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(save)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cancel))
                            .addComponent(avatar, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(anh1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(anh2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(anh3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(anh4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {anh1, anh2, anh3, anh4});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(avatar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cancel)
                    .addComponent(save))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(anh4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(anh1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(anh2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(anh3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {anh1, anh2, anh3, anh4});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        StaticFinalvariable.user.setLink(link);
        this.setVisible(false);
    }//GEN-LAST:event_saveActionPerformed

    private void anh1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anh1ActionPerformed
        // TODO add your handling code here:
        avatar.setIcon(new ImageIcon(new ImageIcon(getClass().getResource(StaticFinalvariable.image[0])).getImage().getScaledInstance(150, 150, Image.SCALE_DEFAULT)));
        link=StaticFinalvariable.image[0];

    }//GEN-LAST:event_anh1ActionPerformed

    private void anh2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anh2ActionPerformed
        // TODO add your handling code here:
        avatar.setIcon(new ImageIcon(new ImageIcon(getClass().getResource(StaticFinalvariable.image[1])).getImage().getScaledInstance(150, 150, Image.SCALE_DEFAULT)));
        link=StaticFinalvariable.image[1];
    }//GEN-LAST:event_anh2ActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_cancelActionPerformed

    private void anh3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anh3ActionPerformed
        // TODO add your handling code here:
        avatar.setIcon(new ImageIcon(new ImageIcon(getClass().getResource(StaticFinalvariable.image[2])).getImage().getScaledInstance(150, 150, Image.SCALE_DEFAULT)));
        link=StaticFinalvariable.image[2];
    }//GEN-LAST:event_anh3ActionPerformed

    private void anh4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anh4ActionPerformed
        avatar.setIcon(new ImageIcon(new ImageIcon(getClass().getResource(StaticFinalvariable.image[3])).getImage().getScaledInstance(150, 150, Image.SCALE_DEFAULT)));
        // TODO add your handling code here:
        link=StaticFinalvariable.image[3];
    }//GEN-LAST:event_anh4ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(avatar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(avatar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(avatar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(avatar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new avatar().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anh1;
    private javax.swing.JButton anh2;
    private javax.swing.JButton anh3;
    private javax.swing.JButton anh4;
    private javax.swing.JLabel avatar;
    private javax.swing.JButton cancel;
    private javax.swing.JButton save;
    // End of variables declaration//GEN-END:variables
}
