/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pikachu;

import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.border.LineBorder;

/**
 *
 * @author Thang
 */
public class Avatar extends javax.swing.JFrame {
private String link;
    /**
     * Creates new form avatars
     */
    public Avatar() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        setTitle("Pick Your Avatar");
        setSize(400,300);
        setResizable(false);
        setLocationRelativeTo(null);
        avatar.setBorder(new LineBorder(Color.yellow, 2));
        anh1.setBorder(new LineBorder(Color.yellow, 2));
        anh2.setBorder(new LineBorder(Color.blue, 2));
        anh3.setBorder(new LineBorder(Color.red, 2));
        anh4.setBorder(new LineBorder(Color.GREEN, 2));
        save.setBackground(Color.green);
        cancel.setBackground(Color.red);
        layout.setSize(400,300);
        layout.setIcon(new ImageIcon(new ImageIcon(getClass().getResource("/pikachu/image/av.jpg")).getImage().getScaledInstance(400, 300, Image.SCALE_DEFAULT)));
        setdata();
    }

    public void setdata() {
        anh1.setIcon(new ImageIcon(new ImageIcon(getClass().getResource(StaticFinalvariable.image[0])).getImage().getScaledInstance(60, 60, Image.SCALE_DEFAULT)));
        anh2.setIcon(new ImageIcon(new ImageIcon(getClass().getResource(StaticFinalvariable.image[1])).getImage().getScaledInstance(60, 60, Image.SCALE_DEFAULT)));
        anh3.setIcon(new ImageIcon(new ImageIcon(getClass().getResource(StaticFinalvariable.image[2])).getImage().getScaledInstance(60, 60, Image.SCALE_DEFAULT)));
        anh4.setIcon(new ImageIcon(new ImageIcon(getClass().getResource(StaticFinalvariable.image[3])).getImage().getScaledInstance(60, 60, Image.SCALE_DEFAULT)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        avatar = new javax.swing.JLabel();
        save = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        anh1 = new javax.swing.JButton();
        anh2 = new javax.swing.JButton();
        anh3 = new javax.swing.JButton();
        anh4 = new javax.swing.JButton();
        layout = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(avatar);
        avatar.setBounds(130, 30, 135, 120);

        save.setText("save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        getContentPane().add(save);
        save.setBounds(130, 160, 55, 23);

        cancel.setText("cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        getContentPane().add(cancel);
        cancel.setBounds(190, 160, 80, 23);

        anh1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anh1ActionPerformed(evt);
            }
        });
        getContentPane().add(anh1);
        anh1.setBounds(30, 200, 65, 55);

        anh2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anh2ActionPerformed(evt);
            }
        });
        getContentPane().add(anh2);
        anh2.setBounds(120, 200, 65, 55);

        anh3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anh3ActionPerformed(evt);
            }
        });
        getContentPane().add(anh3);
        anh3.setBounds(210, 200, 65, 55);

        anh4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anh4ActionPerformed(evt);
            }
        });
        getContentPane().add(anh4);
        anh4.setBounds(300, 200, 65, 55);
        getContentPane().add(layout);
        layout.setBounds(0, 0, 400, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        StaticFinalvariable.user.setLink(link);
        FormRegis fr = new FormRegis();
        fr.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_saveActionPerformed

    private void anh1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anh1ActionPerformed
        // TODO add your handling code here:
        avatar.setIcon(new ImageIcon(new ImageIcon(getClass().getResource(StaticFinalvariable.image[0])).getImage().getScaledInstance(130, 120, Image.SCALE_DEFAULT)));
        link=StaticFinalvariable.image[0];

    }//GEN-LAST:event_anh1ActionPerformed

    private void anh2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anh2ActionPerformed
        // TODO add your handling code here:
        avatar.setIcon(new ImageIcon(new ImageIcon(getClass().getResource(StaticFinalvariable.image[1])).getImage().getScaledInstance(130, 130, Image.SCALE_DEFAULT)));
        link=StaticFinalvariable.image[1];
    }//GEN-LAST:event_anh2ActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
        
        this.setVisible(false);
        FormRegis fr = new FormRegis();
        fr.setVisible(true);
    }//GEN-LAST:event_cancelActionPerformed

    private void anh3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anh3ActionPerformed
        // TODO add your handling code here:
        avatar.setIcon(new ImageIcon(new ImageIcon(getClass().getResource(StaticFinalvariable.image[2])).getImage().getScaledInstance(130, 150, Image.SCALE_DEFAULT)));
        link=StaticFinalvariable.image[2];
    }//GEN-LAST:event_anh3ActionPerformed

    private void anh4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anh4ActionPerformed
        avatar.setIcon(new ImageIcon(new ImageIcon(getClass().getResource(StaticFinalvariable.image[3])).getImage().getScaledInstance(150, 150, Image.SCALE_DEFAULT)));
        // TODO add your handling code here:
        link=StaticFinalvariable.image[3];
    }//GEN-LAST:event_anh4ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anh1;
    private javax.swing.JButton anh2;
    private javax.swing.JButton anh3;
    private javax.swing.JButton anh4;
    private javax.swing.JLabel avatar;
    private javax.swing.JButton cancel;
    private javax.swing.JLabel layout;
    private javax.swing.JButton save;
    // End of variables declaration//GEN-END:variables
}
