/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pikachu;

/**
 *
 * @author Thang
 */
public class beforegame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public beforegame() {
        initComponents();  
        setResizable(false);
        setSize(430,330);
        setLocationRelativeTo(null);
        setTitle("Pikachu");
        user.setText("Welcome to pikachu, "+StaticFinalvariable.user.getUser());
  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        batdau = new javax.swing.JButton();
        tieptuc = new javax.swing.JButton();
        user = new javax.swing.JLabel();
        scoreall = new javax.swing.JButton();
        layout = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        batdau.setBackground(new java.awt.Color(255, 255, 255));
        batdau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pikachu/image/start.png"))); // NOI18N
        batdau.setMaximumSize(new java.awt.Dimension(60, 20));
        batdau.setMinimumSize(new java.awt.Dimension(60, 20));
        batdau.setPreferredSize(new java.awt.Dimension(60, 20));
        batdau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batdauActionPerformed(evt);
            }
        });
        getContentPane().add(batdau);
        batdau.setBounds(60, 30, 80, 30);

        tieptuc.setBackground(new java.awt.Color(255, 153, 0));
        tieptuc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pikachu/image/resume.png"))); // NOI18N
        getContentPane().add(tieptuc);
        tieptuc.setBounds(60, 70, 80, 30);

        user.setFont(new java.awt.Font("MV Boli", 0, 20)); // NOI18N
        user.setText("Welcome to pikachu");
        getContentPane().add(user);
        user.setBounds(10, -10, 260, 40);

        scoreall.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pikachu/image/score.png"))); // NOI18N
        scoreall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scoreallActionPerformed(evt);
            }
        });
        getContentPane().add(scoreall);
        scoreall.setBounds(60, 110, 80, 30);

        layout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pikachu/image/layout.jpg"))); // NOI18N
        getContentPane().add(layout);
        layout.setBounds(0, 0, 430, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void batdauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batdauActionPerformed
        // TODO add your handling code here:
        ingame in = new ingame();
        in.setVisible(true);
        this.setVisible(false);
    
        
    }//GEN-LAST:event_batdauActionPerformed

    private void scoreallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scoreallActionPerformed
        // TODO add your handling code here:
        scoreall sa = new scoreall();
        sa.setVisible(true);
        
    }//GEN-LAST:event_scoreallActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(beforegame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(beforegame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(beforegame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(beforegame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new beforegame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton batdau;
    private javax.swing.JLabel layout;
    private javax.swing.JButton scoreall;
    private javax.swing.JButton tieptuc;
    private javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables
}
