/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pikachu;

/**
 *
 * @author Thang
 */
public class beforegame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public beforegame() {
        initComponents();  
        setResizable(false);
        setSize(430,330);
        setLocationRelativeTo(null);
        jPanel1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        batdau = new javax.swing.JButton();
        tieptuc = new javax.swing.JButton();
        huongdan = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        quaylai = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        layout = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        batdau.setBackground(new java.awt.Color(255, 153, 0));
        batdau.setText("Bắt Đầu");
        batdau.setMaximumSize(new java.awt.Dimension(60, 20));
        batdau.setMinimumSize(new java.awt.Dimension(60, 20));
        batdau.setPreferredSize(new java.awt.Dimension(60, 20));
        batdau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batdauActionPerformed(evt);
            }
        });
        getContentPane().add(batdau);
        batdau.setBounds(60, 30, 90, 30);

        tieptuc.setBackground(new java.awt.Color(255, 153, 0));
        tieptuc.setText("Tiếp Tục");
        getContentPane().add(tieptuc);
        tieptuc.setBounds(60, 70, 90, 30);

        huongdan.setBackground(new java.awt.Color(255, 153, 0));
        huongdan.setText("Hướng Dẫn");
        huongdan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                huongdanActionPerformed(evt);
            }
        });
        getContentPane().add(huongdan);
        huongdan.setBounds(60, 110, 90, 30);

        jPanel1.setLayout(null);

        quaylai.setText("Quay Lại");
        quaylai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quaylaiActionPerformed(evt);
            }
        });
        jPanel1.add(quaylai);
        quaylai.setBounds(200, 133, 90, 30);

        jLabel1.setText("Hướng Dẫn");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(120, 10, 80, 14);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Nhiệm vụ của bạn rất đơn giản , chỉ cần tìm hai hình giống nhau và đường nối giữa 2 hình đó gấp khúc không quá 2 lần, click vào để loại bỏ chúng.\nMỗi lần loại bỏ được 2 hình bạn sẽ ghi điểm, trò chơi hoàn thành khi bạn loại bỏ được hết các hình trươc khi hết giờ, thời gian còn lại càng nhiều điểm của bạn càng cao.\nKhi không còn nước di chuyển trờ chơi sẽ tự động đảo lại hình, số lần đảo là giới hạn. Khi kết thúc trờ chơi điểm số sẽ được cộng thêm số lần đảo.\n");
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 40, 270, 113);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(40, 20, 300, 180);

        layout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pikachu/layout.jpg"))); // NOI18N
        getContentPane().add(layout);
        layout.setBounds(0, 0, 430, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void huongdanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_huongdanActionPerformed
        // TODO add your handling code here:
        jPanel1.setVisible(true);
        batdau.setVisible(false);
        tieptuc.setVisible(false);
        huongdan.setVisible(false);
    }//GEN-LAST:event_huongdanActionPerformed

    private void batdauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batdauActionPerformed
        // TODO add your handling code here:
        ingame in = new ingame();
        in.setVisible(true);
        this.setVisible(false);
    
        
    }//GEN-LAST:event_batdauActionPerformed

    private void quaylaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quaylaiActionPerformed
        // TODO add your handling code here:
        jPanel1.setVisible(false);
           batdau.setVisible(true);
        tieptuc.setVisible(true);
        huongdan.setVisible(true);
    }//GEN-LAST:event_quaylaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(beforegame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(beforegame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(beforegame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(beforegame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new beforegame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton batdau;
    private javax.swing.JButton huongdan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel layout;
    private javax.swing.JButton quaylai;
    private javax.swing.JButton tieptuc;
    // End of variables declaration//GEN-END:variables
}
