/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pikachu;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Image;
import java.net.InetAddress;
import java.net.UnknownHostException;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;

/**
 *
 * @author Hp Pavilion
 */
public class FormRegis extends javax.swing.JFrame {

    private String url;
    private final String user = "admin";
    private final String password = "123456";
    java.sql.Connection connection = null;
    Statement stmt = null;
    ResultSet rs = null;
    PreparedStatement pStmt = null;
    InetAddress ip;

    /**
     * Creates new form FormRegis
     */
    public FormRegis() {
        initComponents();
        setSize(400, 400);
        setTitle("Login");
        setResizable(false);
        setTitle("Form Register");
        setLocationRelativeTo(null);
        layoutRegis.setSize(400,400);
        layoutRegis.setIcon(new ImageIcon(new ImageIcon(getClass().getResource("/pikachu/image/n.jpg")).getImage().getScaledInstance(400, 400, Image.SCALE_DEFAULT)));
        avatar.setBorder(new LineBorder(Color.yellow));
        avatar.setIcon(new ImageIcon(new ImageIcon(getClass().getResource(StaticFinalvariable.user.getLink())).getImage().getScaledInstance(100, 80, Image.SCALE_DEFAULT)));
    }

    public boolean check() {
        return userLogin.getText().equals("") || passLogin.getText().equals("") || repass.getText().equals("");
    }

    public boolean check2() {
        return passLogin.getText().equals(repass.getText().trim());
    }

    public boolean check3() {
        try {
            ip = InetAddress.getLocalHost();
            url = "jdbc:mysql://" + ip.getHostAddress() + "/scorerank?useSSL=false";
            connection = DriverManager
                    .getConnection(url, user, password);
            String sql = "select username from login where username = ?";
            pStmt = connection.prepareStatement(sql);
            pStmt.setString(1, userLogin.getText());
            rs = pStmt.executeQuery();
            if (!rs.next()) {
                return true;
            }
        } catch (SQLException ex) {
            Logger.getLogger(FormRegis.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnknownHostException ex) {
            Logger.getLogger(FormRegis.class.getName()).log(Level.SEVERE, null, ex);
        }
        return false;
    }

    private String MD5(String md5) {
        try {

            java.security.MessageDigest md = java.security.MessageDigest.getInstance("MD5");
            byte[] array = md.digest(md5.getBytes());
            StringBuffer sb = new StringBuffer();
            for (int i = 0; i < array.length; ++i) {
                sb.append(Integer.toHexString((array[i] & 0xFF) | 0x100).substring(1, 3));
            }
            return sb.toString();
        } catch (java.security.NoSuchAlgorithmException e) {
        }
        return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        userLogin = new javax.swing.JTextField();
        choose = new javax.swing.JButton();
        regis = new javax.swing.JButton();
        back = new javax.swing.JButton();
        passLogin = new javax.swing.JPasswordField();
        repass = new javax.swing.JPasswordField();
        avatar = new javax.swing.JLabel();
        showPass = new javax.swing.JCheckBox();
        showPass1 = new javax.swing.JCheckBox();
        layoutRegis = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Username");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(80, 53, 80, 14);

        jLabel2.setText("Password");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 84, 80, 14);

        jLabel3.setText("Re-passwrord");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(80, 115, 80, 14);

        jLabel4.setText("Avatar");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(80, 190, 60, 14);
        getContentPane().add(userLogin);
        userLogin.setBounds(165, 50, 140, 30);

        choose.setText("Choose");
        choose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseActionPerformed(evt);
            }
        });
        getContentPane().add(choose);
        choose.setBounds(170, 240, 100, 23);

        regis.setText("Register");
        regis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regisActionPerformed(evt);
            }
        });
        getContentPane().add(regis);
        regis.setBounds(130, 280, 80, 23);

        back.setText("Back");
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(230, 280, 55, 23);
        getContentPane().add(passLogin);
        passLogin.setBounds(165, 81, 140, 30);
        getContentPane().add(repass);
        repass.setBounds(165, 112, 140, 30);
        getContentPane().add(avatar);
        avatar.setBounds(170, 150, 100, 80);

        showPass.setText("show");
        showPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPassActionPerformed(evt);
            }
        });
        getContentPane().add(showPass);
        showPass.setBounds(314, 80, 70, 23);

        showPass1.setText("show");
        showPass1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPass1ActionPerformed(evt);
            }
        });
        getContentPane().add(showPass1);
        showPass1.setBounds(314, 111, 70, 23);
        getContentPane().add(layoutRegis);
        layoutRegis.setBounds(0, 0, 380, 340);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseActionPerformed
        // TODO add your handling code here:
        Avatar a = new Avatar();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_chooseActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        FormLogin fl = new FormLogin();
        fl.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backActionPerformed

    private void regisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regisActionPerformed
        // TODO add your handling code here:
        if (check() == true) {
            JOptionPane.showMessageDialog(null, "Enter all field please!!!!");
        } else {
            if (check2() == false) {
                JOptionPane.showMessageDialog(null, "re-password is not match");
            } else {
                if (passLogin.getText().length() < 8) {
                    JOptionPane.showMessageDialog(null, "your password is too short");
                } else {
                    if (check3() == true) {
                        try {
                            ip = InetAddress.getLocalHost();
                            url = "jdbc:mysql://" + ip.getHostAddress() + "/scorerank?useSSL=false";
                            connection = DriverManager
                                    .getConnection(url, user, password);
                            String sql = "INSERT INTO login(username, password , linkanh) VALUES(?,?,?);";
                            pStmt = connection.prepareStatement(sql);
                            pStmt.setString(1, userLogin.getText());
                            pStmt.setString(2, MD5(passLogin.getText()));
                            pStmt.setString(3, StaticFinalvariable.user.getLink());
                            int result = pStmt.executeUpdate();
                            if (result > 0) {
                                JOptionPane.showMessageDialog(null, "Success");
                                FormLogin fl = new FormLogin();
                                fl.setVisible(true);
                                this.setVisible(false);
                            } else {
                                JOptionPane.showMessageDialog(null, "Something wrong!!!");

                            }
                        } catch (SQLException ex) {
                            Logger.getLogger(FormRegis.class.getName()).log(Level.SEVERE, null, ex);
                        } catch (UnknownHostException ex) {
                            Logger.getLogger(FormRegis.class.getName()).log(Level.SEVERE, null, ex);
                        }

                    } 
                    else{
                        JOptionPane.showMessageDialog(null, "username is exist");
                    }
                }
            }
        }

    }//GEN-LAST:event_regisActionPerformed

    private void showPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPassActionPerformed
        // TODO add your handling code here:
        if (showPass.isSelected()) {
            passLogin.setEchoChar((char) 0);
        } else {
            passLogin.setEchoChar('*');
        }
    }//GEN-LAST:event_showPassActionPerformed

    private void showPass1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPass1ActionPerformed
        // TODO add your handling code here:
        if (showPass1.isSelected()) {
            repass.setEchoChar((char) 0);
        } else {
            repass.setEchoChar('*');
        }
    }//GEN-LAST:event_showPass1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel avatar;
    private javax.swing.JButton back;
    private javax.swing.JButton choose;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel layoutRegis;
    private javax.swing.JPasswordField passLogin;
    private javax.swing.JButton regis;
    private javax.swing.JPasswordField repass;
    private javax.swing.JCheckBox showPass;
    private javax.swing.JCheckBox showPass1;
    private javax.swing.JTextField userLogin;
    // End of variables declaration//GEN-END:variables
}
