/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pikachu;

import java.awt.Color;
import java.net.InetAddress;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Hp Pavilion
 */
public class FormLogin extends javax.swing.JFrame {

    private String url;
    private final String user = "admin";
    private final String password = "123456";
    Connection connection = null;
    Statement stmt = null;
    ResultSet rs = null;
    PreparedStatement pStmt = null;
    InetAddress ip;

    /**
     * Creates new form FormLogin
     */
    public FormLogin() {
        initComponents();
        this.setSize(400, 300);
        setTitle("Form Login");
        setResizable(false);
        setLocationRelativeTo(null);
//        register.setOpaque(false);
//        layoutlogin.setSize(280,290);
//jLabel3.setVisible(false);
        //login.setBackground(Color.red);
    }

    public boolean checkrong() {
        return userLogin.getText().equals("") || passLogin.getText().equals("");
    }

    private String MD5(String md5) {
        try {

            java.security.MessageDigest md = java.security.MessageDigest.getInstance("MD5");
            byte[] array = md.digest(md5.getBytes());
            StringBuffer sb = new StringBuffer();
            for (int i = 0; i < array.length; ++i) {
                sb.append(Integer.toHexString((array[i] & 0xFF) | 0x100).substring(1, 3));
            }
            return sb.toString();
        } catch (java.security.NoSuchAlgorithmException e) {
        }
        return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        userLogin = new javax.swing.JTextField();
        login = new javax.swing.JButton();
        register = new javax.swing.JButton();
        passLogin = new javax.swing.JPasswordField();
        showpass = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        layoutlogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("User");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(80, 100, 60, 14);

        jLabel2.setText("Password");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 140, 60, 14);
        getContentPane().add(userLogin);
        userLogin.setBounds(150, 90, 134, 30);

        login.setText("Login");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        getContentPane().add(login);
        login.setBounds(100, 200, 70, 23);

        register.setText("Register");
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });
        getContentPane().add(register);
        register.setBounds(190, 200, 90, 23);
        getContentPane().add(passLogin);
        passLogin.setBounds(150, 130, 134, 30);

        showpass.setText("show");
        showpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showpassActionPerformed(evt);
            }
        });
        getContentPane().add(showpass);
        showpass.setBounds(290, 130, 70, 23);

        jLabel3.setFont(new java.awt.Font("MV Boli", 0, 30)); // NOI18N
        jLabel3.setText("LOGIN");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(150, 10, 190, 50);
        getContentPane().add(layoutlogin);
        layoutlogin.setBounds(0, 0, 350, 290);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
        // TODO add your handling code here:v
        FormRegis fr = new FormRegis();
        fr.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_registerActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
        if (checkrong() == true) {
            JOptionPane.showMessageDialog(null, "Please enter user and password");

        } else {
            try {
                ip = InetAddress.getLocalHost();
                url = "jdbc:mysql://" + ip.getHostAddress() + "/scorerank?useSSL=false";
                connection = DriverManager
                        .getConnection(url, user, password);
                String sql = "select * from login where username=? and password=?";
                pStmt = connection.prepareStatement(sql);
                pStmt.setString(1, userLogin.getText());
                pStmt.setString(2, MD5(passLogin.getText()));
                rs = pStmt.executeQuery();
                if (rs.next()) {
                    this.setVisible(false);
                    StaticFinalvariable.user.setUser(userLogin.getText());
                    beforegame bf = new beforegame();
                    bf.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(this, "User or password is not correct");
                    userLogin.setText("");
                    passLogin.setText("");
                }
            } catch (Exception e) {
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_loginActionPerformed

    private void showpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showpassActionPerformed
        // TODO add your handling code here:
        if (showpass.isSelected()) {
            passLogin.setEchoChar((char) 0);
        } else {
            passLogin.setEchoChar('*');
        }
    }//GEN-LAST:event_showpassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel layoutlogin;
    private javax.swing.JButton login;
    private javax.swing.JPasswordField passLogin;
    private javax.swing.JButton register;
    private javax.swing.JCheckBox showpass;
    private javax.swing.JTextField userLogin;
    // End of variables declaration//GEN-END:variables
}
