/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pikachu;

import java.awt.BorderLayout;
import java.awt.FlowLayout;
import java.awt.GridBagLayout;
import java.awt.GridLayout;
import java.util.Locale;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;

/**
 *
 * @author Thang
 */
public class ingame extends javax.swing.JFrame {

    /**
     * Creates new form ingame
     */
    public ingame() {
        initComponents();
        setSize(850,600);
        setResizable(false);
        setTitle("Pikachu Game");
        layout.setSize(850,600);
//      layoutpikachu.setOpaque();
        layoutpikachu.setBackground(null);
        layoutpikachu.setSize(700,400);
        setLocationRelativeTo(null);
        play.setEnabled(false);
       
        MyGridLayout();
        
    }
    public void MyGridLayout(){
        GridLayout grid = new GridLayout(9,16,2,2);

        layoutpikachu.setLayout(grid);
        String[] buttons =  new String[144];
        for (int i = 0; i < buttons.length; i++) {
                JButton but = new JButton();
               
                but.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pikachu/icon8.jpg")));
                layoutpikachu.add(but); 
                
        }
        layoutpikachu.setOpaque(false);
           
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        layoutpikachu = new javax.swing.JPanel();
        newgame = new javax.swing.JButton();
        pause = new javax.swing.JButton();
        time = new javax.swing.JLabel();
        reset = new javax.swing.JButton();
        score = new javax.swing.JButton();
        play = new javax.swing.JButton();
        diem = new javax.swing.JLabel();
        hint = new javax.swing.JButton();
        layout = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        javax.swing.GroupLayout layoutpikachuLayout = new javax.swing.GroupLayout(layoutpikachu);
        layoutpikachu.setLayout(layoutpikachuLayout);
        layoutpikachuLayout.setHorizontalGroup(
            layoutpikachuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );
        layoutpikachuLayout.setVerticalGroup(
            layoutpikachuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );

        getContentPane().add(layoutpikachu);
        layoutpikachu.setBounds(120, 30, 410, 340);

        newgame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pikachu/3.png"))); // NOI18N
        newgame.setBorder(null);
        newgame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newgameActionPerformed(evt);
            }
        });
        getContentPane().add(newgame);
        newgame.setBounds(10, 130, 80, 35);

        pause.setText("Pause");
        pause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pauseActionPerformed(evt);
            }
        });
        getContentPane().add(pause);
        pause.setBounds(10, 180, 100, 30);

        time.setText("Thời gian");
        getContentPane().add(time);
        time.setBounds(120, 10, 70, 14);

        reset.setText("reset");
        getContentPane().add(reset);
        reset.setBounds(10, 260, 100, 30);

        score.setText("score");
        score.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scoreActionPerformed(evt);
            }
        });
        getContentPane().add(score);
        score.setBounds(10, 300, 100, 30);

        play.setText("Play");
        play.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playActionPerformed(evt);
            }
        });
        getContentPane().add(play);
        play.setBounds(10, 220, 100, 30);

        diem.setText("Điểm: 0");
        getContentPane().add(diem);
        diem.setBounds(490, 10, 70, 14);

        hint.setText("hint");
        getContentPane().add(hint);
        hint.setBounds(20, 30, 73, 23);

        layout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pikachu/Sleep-Pikachu-Pokemon-Wallpaper.png"))); // NOI18N
        getContentPane().add(layout);
        layout.setBounds(0, 0, 610, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void scoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scoreActionPerformed
        // TODO add your handling code here:
        scorerank sr = new scorerank();
        sr.setVisible(true);
        
    }//GEN-LAST:event_scoreActionPerformed

    private void newgameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newgameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newgameActionPerformed

    private void pauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pauseActionPerformed
        // TODO add your handling code here:
        layoutpikachu.setVisible(false);
        pause.setEnabled(false);
        play.setEnabled(true);
    }//GEN-LAST:event_pauseActionPerformed

    private void playActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playActionPerformed
        // TODO add your handling code here:
        layoutpikachu.setVisible(true);
        play.setEnabled(false);
        pause.setEnabled(true);
    }//GEN-LAST:event_playActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ingame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ingame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ingame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ingame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ingame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel diem;
    private javax.swing.JButton hint;
    private javax.swing.JLabel layout;
    private javax.swing.JPanel layoutpikachu;
    private javax.swing.JButton newgame;
    private javax.swing.JButton pause;
    private javax.swing.JButton play;
    private javax.swing.JButton reset;
    private javax.swing.JButton score;
    private javax.swing.JLabel time;
    // End of variables declaration//GEN-END:variables
}
